# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  nix:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v8
      with:
        name: coq
    - run: nix-build

  opam:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        coq_version:
          - '8.11'
          - '8.12'
          - '8.13'
        ocaml_version:
          - 'minimal'
    steps:
    - uses: actions/checkout@v2
    - uses: coq-community/docker-coq-action@v1
      with:
        opam_file: './coq-hierarchy-builder.opam'
        coq_version: ${{ matrix.coq_version }}
        ocaml_version: ${{ matrix.ocaml_version }}
        after_script: |
          mkdir /home/coq/workspace
          cd /home/coq/workspace
          git clone https://github.com/gares/math-comp
          cd math-comp
          git checkout hierarchy-builder
          cd mathcomp
          make -j2 algebra/ssralg.vo
